// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig,env } from "prisma/config";

// console.log(process.env.DATABASE_URL, process.env.DIRECT_URL)
console.log(env("DATABASE_URL"), env("DIRECT_URL"))

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env('DIRECT_URL'),
  },
});
